<a href="https://colab.research.google.com/github/insooAI/hello-world/blob/main/2015318434_ml_project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# train, test data
df = pd.read_csv('/content/drive/My Drive/데이터/TRAIN.csv',encoding='UTF-8')[['Post','Label']]  
tdf = pd.read_csv('/content/drive/My Drive/데이터/TEST.csv',encoding='UTF-8')

In [ ]:
tdf["Label"] = 'Unknown'

In [ ]:
df = pd.concat([df,tdf],axis=0)

In [ ]:
posts = df["Post"].values.tolist()
labels = df["Label"].values.tolist()

In [ ]:
import pandas as pd
import nltk
import numpy as np
nltk.download("wordnet")
nltk.download("stopwords")
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
import re                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                              
def cleanHtml(raw_html):                                                                                      
    cleanr = re.compile('<.*?>')                                                                              
    cleantext = re.sub(cleanr, '', raw_html)                                                                  
    return cleantext                                                                                          
                                                                                                              
def etcRemove(x) :                                                                                         
    return re.sub('[^0-9a-zA-Zㄱ-ㅎ가-힣${3}#{3}| |,|.|!|?|`|\']', "",x)                                               
                                                                                                                                                                                                                                                                                                                                                                                              
def removeURL(x) :                                                                                                                                                                                                                                                                                                                                                                            
    return re.sub("(https|http|ftp|telnet|news|mms)?://(\w*:\w*@)?[-\w.]+(:\d+)?(/([\w/_.]*(\?\S+)?)?)?","",x)

def tolower(x) :                                                                                                                                                                                                                                                                                                                                                                              
    try :                                                                                                                                                                                                                                                                                                                                                                                     
        return x.lower()                                                                                                                                                                                                                                                                                                                                                                      
    except :                                                                                                                                                                                                                                                                                                                                                                                  
        return "" 

from nltk.corpus import stopwords


def prep(x) :
    
    return tolower(etcRemove(cleanHtml(removeURL(x))))

def remove_stopwords(x): 
    stops= set(stopwords.words('english'))

    mystops = ["shed","dont","didnt","youre","im","its","wentare","shes","hes"]

    stops = list(stops) + mystops

    no_stops = [word for word in x if not word in stops]
    return list(no_stops)


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [ ]:
posts = list( prep(x) for x in posts ) 

In [ ]:
def tokenize(line) :
    return nltk.word_tokenize(line)
#단어별 토큰화

def extract(lines) :
    tokens = list( nltk.pos_tag(tokenize(line)) for line in lines)  
    return list( list( (x[0],x[1]) for x in y if x[1][:2] == "NN" or x[1][:2] == "VB" ) for y in tokens )
# 동사와 명사만 추출

In [ ]:
tokens = extract(posts)

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
tokens = list( list(lemmatizer.lemmatize(word,'v') for word,tag in x) for x in tokens)
# 원형 복원

In [ ]:
tokens = list(remove_stopwords(x) for x in tokens )
#불용어 제거

In [ ]:
def count_words(posts) :
    d = {} 

    for p in posts : 
        for w in p :
            try :
                d[w] += 1   
            except :
                d[w] = 1

    return d

In [ ]:
word_count = count_words(tokens)

In [ ]:
tokens = list( list( x for x in y if word_count[x] > 1) for y in tokens)

In [ ]:
word_count = count_words(tokens)

In [ ]:
sorted(word_count.items(), key=lambda x: x[1], reverse=False)


[("'wanting", 2),
 ('kitty', 2),
 ('better.you', 2),
 ('ideations', 2),
 ('horrible', 2),
 ('hawaii', 2),
 ('errands', 2),
 ("'my", 2),
 ('powerless', 2),
 ('eerie', 2),
 ('revolution', 2),
 ('outpouring', 2),
 ('timeframe', 2),
 ('clearer', 2),
 ('times.im', 2),
 ('salvation', 2),
 ('amusement', 2),
 ('intoxicate', 2),
 ('paul', 2),
 ('struggeling', 2),
 ('suicde', 2),
 ('again..', 2),
 ('sweetheart', 2),
 ('gentler', 2),
 ('underlie', 2),
 ('cable', 2),
 ('gently', 2),
 ('allergies', 2),
 ('wheres', 2),
 ('bell', 2),
 ('panel', 2),
 ('dork', 2),
 ('zap', 2),
 ('extension', 2),
 ('that.im', 2),
 ('can.a', 2),
 ("'gti", 2),
 ('meaninglessness', 2),
 ('life.if', 2),
 ('consideration', 2),
 ('sicker', 2),
 ('dissonance', 2),
 ('you.do', 2),
 ('selfcare', 2),
 ('youxe2x80x99ll', 2),
 ('council', 2),
 ('gollum', 2),
 ('birthgiver', 2),
 ('prognosis', 2),
 ('gaslighting', 2),
 ('landlords', 2),
 ('scam', 2),
 ('cult', 2),
 ('promotions', 2),
 ('complex', 2),
 ('grandparent', 2),
 ('alcoholi

In [ ]:
dataset = list(zip(tokens,labels))
len(dataset)

500

In [ ]:
# dataset에 있는 모든 단어 집합
totalnouns = list(set(sum(list( x[0] for x in dataset ),[])))

In [ ]:
label_score = {
        "Supportive" :4,
        "Behavior" : 1,
        "Ideation": 2,
        "Indicator": 3,
        "Attempt"  : 0,
        "Unknown" : -1
    }

In [ ]:
dataset = list( (x[0],label_score[x[1]]) for x in dataset )

In [ ]:
def make_vocab_dict(tnouns) :
  idx = 0
  word_idx_dict = {}
  idx_word_dict = {}

  for nouns in tnouns :
    word_idx_dict[nouns] = idx
    idx_word_dict[idx] = nouns
    idx += 1

  return word_idx_dict,idx_word_dict

wi,iw = make_vocab_dict(totalnouns)
total_noun_cnt = len(wi.items())

def encode_post(post,total_noun_cnt,wi) :
  bow = [ 0 for _ in range(total_noun_cnt) ]

  for w in post :
    idx = wi[w]
    bow[idx] +=  1

  return bow

def encode_all_post(dataset,total_noun_cnt,wi) :

  bows = []

  for post,label in dataset :
    bow = encode_post(post,total_noun_cnt,wi)
    bows.append(bow)

  return bows


bows = encode_all_post(dataset,total_noun_cnt,wi)

In [ ]:
def count_word_for_post(post) :
  d = {}
  for w in post :
    try :
      d[w] += 1
    except :
      d[w] = 1

  return d

def make_df(bows,word_count) :
  df = {}

  for i in range(word_count) : 
    df[i] = 0

    for d in bows :
      if d[i] > 0 :
        df[i] += 1

  return df

from math import log

def tf_idf(bows,word_count,df) :
  nd = len(bows)
  
  idf_scores = [ [0 for _ in range(word_count)] for x in range(len(bows)) ]
  doc_idx = 0

  for d in bows :
    tcnt = sum(d)
    
    for word_idx in range(word_count) :
      mother = 1 + df[word_idx]  
      son = nd
      idf_scores[doc_idx][word_idx] = (log(son/mother)+1) * (d[word_idx]/tcnt)
       
    doc_idx += 1
     
  return idf_scores

df = make_df(bows,total_noun_cnt)
tf_idf_array = tf_idf(bows,total_noun_cnt,df)


In [ ]:
class LinearModel :
    def __init__(self) :
        pass

    def initW(self,pcodes) :
        a = []
        wa = []
        tw = np.sum(pcodes)

        return np.ones(len(pcodes[0])) / tw
       

    def initB(self,pcodes) :
        return -2

    def gradfn(self,xp,s) :
        return -self.X[xp] * 0.000001 * s     #가중치 행렬에 대한 학습률

    def _train(self,xp) :
        loss = self.L[xp]

        gd = self.gradfn(xp,loss)

        self.w += gd
        self.b -= loss * 0.000001    #bias에 대한 학습률
       # print(self.L[xp])

    def train(self) :
        for i in range(len(self.X)) :
            self._train(i)
            print(np.sum(self.L))

    def run(self,x,y,di,dd,mc,epoch) :
        X = np.array(x)
        Y = y

        self.X = X

        self.w = self.initW(X)
        self.Y = Y  
        self.b = self.initB(X)

        for _ in range(epoch) :
            self.P = np.matmul(X,self.w.T) + self.b  
            self.L = self.P - self.Y  

            self.train()
        
        return self.w,self.b

    def predict(self,x,dd,mc)  :
        X = np.array(x)

        P = np.matmul(X,self.w.T) + self.b
        predicts = []

        for i in range(len(X)) :
            p = min(int(P[i]+0.5),4)
            predicts.append(p)

        return predicts



In [ ]:
# 일단 제외
model = LinearModel()

train_x = list( list(y*60  for y in x) for x in tf_idf_array[:350] )
train_y = list( x[1] for x in dataset[:350] )

test_x = list( list(y*60  for y in x) for x in tf_idf_array[350:] )
test_y = list( x[1] for x in dataset[350:] )


In [ ]:

model = LinearModel()

train_x = list( list(y*60  for y in x) for x in tf_idf_array[:200] )
train_y = list( x[1] for x in dataset[:200] )

test_x = list( list(y*60  for y in x) for x in tf_idf_array[200:350] )
test_y = list( x[1] for x in dataset[200:350] )


In [ ]:
# 모델 피팅
model.run(train_x,train_y,wi,iw,total_noun_cnt,epoch=2000)


In [ ]:
# y 값 예측
pred_y = model.predict(test_x,iw,total_noun_cnt)
print(pred_y)
import pandas as pd 

pd.DataFrame(pred_y).to_csv("2015318434.csv",index=False)

[2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 1, 1, 2, 2, 2, 3, 2, 2, 1, 1, 2, 2, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 1, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 3, 2, 2, 2, 1, 2, 2, 3, 2, 2, 3, 2, 2, 3, 1, 2, 3, 2, 3, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 2, 3, 0, 2, 1, 2, 2, 2, 1, 2, 2, 3, 2, 3, 2, 2, 2, 2, 3, 2, 2, 1, 3, 2, 2, 3, 2, 1, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 3, 2]


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
def get_clf_eval(test,pred):
  confusion = confusion_matrix(test,pred)
  accuracy = accuracy_score(test,pred)
  print(confusion)
  print('정확도: {0:.4f}'.format(accuracy))

get_clf_eval(test_y,pred_y)

[[ 0  2  6  2  0]
 [ 0  7 15  1  0]
 [ 0  5 43 10  0]
 [ 0  1 23  5  0]
 [ 1  3 13 13  0]]
정확도: 0.3667
